### ISSUE TITLE
As a UX Research founding member, I need to issue a survey, so that we can find the best time to meet (and cadence).

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/ux-research#6]
update: First, the group should vote on a time for the _first meeting_. During that meeting you can decide how often you want to meet as a group. 

At your first meeting, the group should decide when and how often you can meet. Weekly, monthly, yearly? How often do you intend to meet? What time works for the existing group? How can we address any potential changes to availability?

**Comment by mrmetaverse** [comment]
Group was approved, I know we were having some trouble finding a good tool for finding the best time. I have a new resource in my savvycal we can try if you'd like? 

https://savvycal.com/p/mrmetaverse/ee3f5168

**Comment by benediktwoelk** [comment]
I just tried savvycal and picked one time slot that works for me. However, it is a bit confusing that a date in the past is shown. I assume we are just interested in the time slot and then decide on a cadence separately (weekly/bi-weekly/monthly).

**Comment by mrmetaverse** [comment]
Yeah, I think at this phase, we are voting on the best time to meet to kick off the group, and during that kickoff, those who are participating can decide when / how-often they want to meet.

**Comment by Elirudite** [comment]
Seems like the last savvycal link was limited to a few weeks, so hopefully people can vote on their times here: https://savvycal.com/omi-ux-group/4ebf2523 

However, we may need to directly @ people on discord to make sure more people actually vote.

**Comment by mrmetaverse** [comment]
![Screenshot_20221012-112541.png](https://user-images.githubusercontent.com/63426722/195384252-99b67cf6-7291-4857-b3da-d390ff6965bd.png)

**Comment by mrmetaverse** [comment]
# UX Research group 
the group will kick off on Tuesday 10/18/22 at 16:00 UTC! SPREAD THE WORD <3
